name: Start a run from Jupyter Notebook on local server via self-hosted Github Actions runner

on:
  push:
    branches:
      - development
    paths:
      - 'notebooks/**'

jobs:
  run-notebook-in-development-environment:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
        
    - name: Install dependencies
      run: |
        source ~/mlops-venv/bin/activate
        python -m pip install --upgrade pip
        pip install jupyter
        python -m pip install kfp==1.8.22
        
    - name: Connect to local server and run the Notebook      
      run: |       
        source ~/mlops-venv/bin/activate
        jupyter nbconvert --execute --to notebook --inplace notebooks/demo-pipeline.ipynb